words = [
    { text: 'Salut', translation: 'הי', partOfSpeech: 'greeting' },
    { text: 'Bonjour', translation: 'שלום', partOfSpeech: 'greeting' },
    { text: "Comment tu t'appelles ?", translation: 'איך קוראים לך?', partOfSpeech: 'phrase' },
    { text: "je m’appelle", translation: 'שמי הוא', partOfSpeech: 'phrase' },
    { text: "un collège", translation: 'חטיבת ביניים', partOfSpeech: 'noun' },
    { text: "un cahier", translation: 'מחברת', partOfSpeech: 'noun' },
    { text: "un cahier d’exercices", translation: 'מחברת תרגולים', partOfSpeech: 'noun' },
    { text: "un professeur de français", translation: 'מורה לצרפתית', partOfSpeech: 'noun' },
    { text: "une classe", translation: 'כיתה', partOfSpeech: 'noun' },
    { text: "une école", translation: 'בית ספר', partOfSpeech: 'noun' },
    { text: "une année", translation: 'שנה', partOfSpeech: 'noun' },
    { text: "excuse-moi", translation: 'סלח לי', partOfSpeech: 'phrase' },
    { text: "une voiture", translation: 'מכונית', partOfSpeech: 'noun' },
    { text: "qui est absent aujourd’hui?", translation: 'מי נעדר היום?', partOfSpeech: 'phrase' },
    { text: "absent / absente", translation: 'נעדר / נעדרת', partOfSpeech: 'adjective' },
    { text: "un citron", translation: 'לימון', partOfSpeech: 'noun' },
    { text: "un cinéma", translation: 'קולנוע', partOfSpeech: 'noun' },
    { text: "un gâteau", translation: 'עוגה', partOfSpeech: 'noun' },
    { text: "une glace", translation: 'גלידה', partOfSpeech: 'noun' },
    { text: "une girafe", translation: "ג'ירפה", partOfSpeech: 'noun' },
    { text: "une signature", translation: 'חתימה', partOfSpeech: 'noun' },
    { text: "tu parles français?", translation: 'אתה מדבר צרפתית?', partOfSpeech: 'phrase' },
    { text: "tu es français?", translation: 'אתה צרפתי?', partOfSpeech: 'phrase' },
    { text: "une fille", translation: 'ילדה', partOfSpeech: 'noun' },
    { text: "un garçon", translation: 'ילד', partOfSpeech: 'noun' },
    { text: "des amis", translation: 'חברים', partOfSpeech: 'noun' },
    { text: "un chat", translation: 'חתול', partOfSpeech: 'noun' },
    { text: "un chien", translation: 'כלב', partOfSpeech: 'noun' },
    { text: "pardon pour le retard", translation: 'סליחה על האיחור', partOfSpeech: 'phrase' },
    { text: "présent / présente", translation: 'נוכח / נוכחת', partOfSpeech: 'adjective' }
];
