const words = [
    { text: 'test', translation: 'מבחן' },
    { text: 'teacher', translation: 'מורה' },
    { text: 'pen', translation: 'עט' },
    { text: 'pencil', translation: 'עיפרון' },
    { text: 'hat', translation: 'כובע' },
    { text: 'add', translation: 'להוסיף' },
    { text: 'plus', translation: 'פלוס' },
    { text: 'elephant', translation: 'פיל' },
    { text: 'egg', translation: 'ביצה' },
    { text: 'eraser', translation: 'מחק' },
    { text: 'school', translation: 'בית ספר' },
    { text: 'bed', translation: 'מיטה' },
    { text: 'table', translation: 'שולחן' },
    { text: 'let’s', translation: 'בואו' },
    { text: 'go to', translation: 'ללכת אל' },
    { text: 'big', translation: 'גדול' },
    { text: 'breakfast', translation: 'ארוחת בוקר' },

    { text: 'I', translation: 'אני' },
    { text: 'everyday', translation: 'כל יום' },
    { text: '⁠pencil case', translation: 'קלמר' },
    { text: 'sleep', translation: 'שינה' },
];