  words = [
    { text: 'Salut', translation: 'הי' },
    { text: 'Bonjour', translation:  'שלום' },
    { text: "Comment tu t'appelles ?", translation: 'איך קוראים לך?' },
    { text: "je m’appelle", translation: 'שמי הוא' },
    { text: "un collège", translation: 'חטיבת ביניים' },
    { text: "un cahier", translation: 'מחברת' },
    { text: "un cahier d’exercices", translation: 'מחברת תרגולים' },
    { text: "un professeur de français", translation: 'מורה לצרפתית' },
    { text: "une classe", translation: 'כיתה' },
    { text: "une école", translation: 'בית ספר' },
    { text: "une année", translation: 'שנה' },
    { text: "excuse-moi", translation: 'סלח לי' },
    { text: "une voiture", translation: 'מכונית' },
    { text: "qui est absent aujourd’hui?", translation: 'מי נעדר היום?' },
    { text: "absent / absente", translation: 'נעדר / נעדרת' },
    { text: "un citron", translation: 'לימון' },
    { text: "un cinéma", translation: 'קולנוע' },
    { text: "un gâteau", translation: 'עוגה' },
    { text: "une glace", translation: 'גלידה' },
    { text: "une girafe", translation: "ג'ירפה" },
    { text: "une signature", translation: 'חתימה' },
    { text: "tu parles français?", translation: 'אתה מדבר צרפתית?' },
    { text: "tu es français?", translation: 'אתה צרפתי?' },
    { text: "une fille", translation: 'ילדה' },
    { text: "un garçon", translation: 'ילד' },
    { text: "des amis", translation: 'חברים' },
    { text: "un chat", translation: 'חתול' },
    { text: "un chien", translation: 'כלב' },
    { text: "pardon pour le retard", translation: 'סליחה על האיחור' },
    { text: "présent / présente", translation: 'נוכח / נוכחת' }
];
