words = [
    { text: "imagine", translation: 'לדמיין' },
    { text: "prefer", translation: 'להעדיף' },
    { text: "realize", translation: 'להבין' },
    { text: "careful", translation: 'זהיר' },
    { text: "dangerous", translation: 'מסוכן' },
    { text: "possible", translation: 'אפשרי' },
    { text: "unusual", translation: 'יוצא דופן' },
    { text: "usual", translation: 'רגיל' },
    { text: "wide", translation: 'רחב' },
    { text: "bowl", translation: 'קערה' },
    { text: "guide", translation: 'מדריך' },
    { text: "history", translation: 'היסטוריה' },
    { text: "job", translation: 'עבודה' },
    { text: "lemon", translation: 'לימון' },
    { text: "meal", translation: 'ארוחה' },
    { text: "oil", translation: 'שמן' },
    { text: "pepper", translation: 'פלפל' },
    { text: "salt", translation: 'מלח' },
    { text: "world", translation: 'עולם' },
    { text: "nation", translation: 'אומה' },
    { text: "amaze", translation: 'להדהים' },
    { text: "fall in love", translation: 'להתאהב' },
    { text: "feed", translation: 'להאכיל' },
    { text: "follow", translation: 'לעקוב' },
    { text: "open", translation: 'פתוח' },
    { text: "receive", translation: 'לקבל' },
    { text: "serve", translation: 'להגיש' },
    
]