words = [
    { text: "activity", translation: 'פעילות' },
    { text: "bridge", translation: 'גשר' },
    { text: "choice", translation: 'בחירה' },
    { text: "danger", translation: 'סכנה' },
    { text: "journey", translation: 'מסע' },
    { text: "mountain", translation: 'הר' },
    { text: "river", translation: 'נהר' },
    { text: "village", translation: 'כפר' },
    { text: "across", translation: 'לעבור' },
    { text: "any", translation: 'שום דבר' },
    { text: "anybody", translation: 'אף אחד/כל אחד' },
    { text: "directly", translation: 'ישירות' },
    { text: "next to", translation: 'ליד' },
    { text: "continue", translation: 'להמשיך' },
    { text: "depend on", translation: 'להסתמך על' },
    { text: "fix", translation: 'לתקן' },
    { text: "shake hands", translation: 'ללחוץ ידיים' },
    { text: "welcome", translation: 'ברוכים הבאים' },
    { text: "amazing", translation: 'מדהים' },
    { text: "certain", translation: 'בטוח' },
    { text: "lovely", translation: 'נחמד' },
    { text: "main", translation: 'עיקרי' },
    { text: "typica", translation: ' טיפוסי' },
    { text: "warm", translation: 'חם' },
    { text: "according to", translation: 'לפי' }
    
]