words = [
    {text: "cat", translation: 'חתול'},
    {text: "dog", translation: 'כלב'},
    {text: "fish", translation: 'דג'},
    {text: "bird", translation: 'ציפור'},
    {text: "cow", translation: 'פרה'},
    {text: "horse", translation: 'סוס'},
    {text: "sheep", translation: 'כבש'},
    {text: "pig", translation: 'חזיר'},
    {text: "mouse", translation: 'עכבר'},
    {text: "elephant", translation: 'פיל'},
    {text: "lion", translation: 'אריה'},
    {text: "monkey", translation: 'קוף'},
    {text: "bear", translation: 'דוב'},
    {text: "tiger", translation: 'נמר'},
    {text: "rabbit", translation: 'ארנב'},
    {text: "duck", translation: 'ברווז'},
    {text: "turtle", translation: 'צב'},
    {text: "frog", translation: 'צפרדע'},
    {text: "deer", translation: 'אייל'},
    {text: "kangaroo", translation: 'קנגרו'},
    {text: "zebra", translation: 'זברה'},
    {text: "penguin", translation: 'פינגווין'},
    {text: "owl", translation: 'ינשוף'},
    {text: "snail", translation: 'חילזון'},
    {text: "ant", translation: 'נמלה'},
    {text: "bee", translation: 'דבורה'},
    {text: "butterfly", translation: 'פרפר'},
    {text: "spider", translation: 'עכביש'},
    {text: "scorpion", translation: 'עקרב'},
    {text: "mosquito", translation: 'יתוש'},
    {text: "fly", translation: 'זבוב'},
    
];
