words = [
    { text: "happy", translation: 'שמח' },
    { text: "sad", translation: 'עצוב' },
    { text: "angry", translation: 'כועס' },
    { text: "excited", translation: 'נרגש' },
    { text: "bored", translation: 'משועמם' },
    { text: "scared", translation: 'מפחד' },
    { text: "nervous", translation: 'עצבני' },
    { text: "surprised", translation: 'מופתע' },
    { text: "calm", translation: 'רגוע' },
    { text: "tired", translation: 'עייף' },
    { text: "worried", translation: 'דואג' },
    { text: "hopeful", translation: 'מקווה' },
    { text: "lonely", translation: 'בודד' },
    { text: "confused", translation: 'מבולבל' },
    { text: "proud", translation: 'גאה' },
    { text: "embarrassed", translation: 'מבוכה' },
    { text: "jealous", translation: 'קנאי' },
    { text: "grateful", translation: 'אסיר תודה' },
    { text: "amazed", translation: 'נדהם' },
    { text: "satisfied", translation: 'מרוצה' },
    { text: "relieved", translation: 'מרוחק' },
    { text: "disappointed", translation: 'מאוכזב' },
    { text: "curious", translation: 'סקרן' },
    { text: "frustrated", translation: 'מתוסכל' },
    { text: "optimistic", translation: 'אופטימי' }
];
