words = [
    { text: "wizard", translation: 'קוסם' },
    { text: "witch", translation: 'מכשפה' },
    { text: "magic", translation: 'קסם' },
    { text: "wand", translation: 'מטה' },
    { text: "broomstick", translation: 'מטאטא' },
    { text: "spell", translation: 'לחש' },
    { text: "potion", translation: 'שיקוי' },
    { text: "owl", translation: 'ינשוף' },
    { text: "goblin", translation: 'גובלין' },
    { text: "castle", translation: 'טירה' },
    { text: "ghost", translation: 'רוח רפאים' },
    { text: "quidditch", translation: 'קווידיץ' },
    { text: "hogwarts", translation: 'הוגוורטס' },
    { text: "muggle", translation: 'מאגל' },
    { text: "dumbledore", translation: 'דמבלדור' },
    { text: "voldemort", translation: 'וולדמורט' },
    { text: "hermione", translation: 'הרמיוני' },
    { text: "ron", translation: 'רון' },
    { text: "harry", translation: 'הארי' },
    { text: "snape", translation: 'סנייפ' },
    { text: "hagrid", translation: 'הגריד' },
    { text: "gryffindor", translation: 'גריפינדור' },
    { text: "ravenclaw", translation: 'רייבנקלו' },
    { text: "hufflepuff", translation: 'האפלפאף' }
];
